[package]
namespace   = "mcpplibs.capi"
name        = "lua"
version     = "0.0.3"
description = "C++23 module wrapping the Lua 5.4 C API — import mcpplibs.capi.lua;"
license     = "Apache-2.0"
repo        = "https://github.com/mcpplibs/lua"

[lib]
path = "src/capi/lua.cppm"

[targets.capi-lua]
kind = "lib"

[dependencies.compat]
lua = "5.4.7"

[dev-dependencies.compat]
gtest = "1.15.2"
